#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Apply ground calibration as a vehicle-forward BEV transform.

This script reads ground_extrinsic.yaml generated by charuco_ground_extrinsic.py.
It converts the ChArUco-board ground frame into a vehicle-style ground frame:

  Vehicle frame on ground:
    Xv: forward
    Yv: left
    Zv: up/ground normal conceptually, but only Xv-Yv plane is used here

  BEV image convention:
    image up    = +Xv forward
    image left  = +Yv left
    image right = -Yv right

Default alignment:
  --align camera-optical
  It projects the camera optical axis onto the ground plane and treats that as vehicle forward.
  This is usually correct when the camera is mounted facing the car's forward direction.

Typical usage:
  python3 apply_vehicle_bev.py \
    --extrinsic ~/calib/extrinsics/charuco_ground_extrinsic_out/ground_extrinsic.yaml \
    --input ~/calib/test \
    --output ~/calib/test_vehicle_bev \
    --forward-min 0.0 --forward-max 2.0 \
    --left-min -0.6 --left-max 0.6 \
    --ppm 250 \
    --draw-grid
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from pathlib import Path
from typing import Iterable, List, Tuple

import cv2
import numpy as np


IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp"}


def list_images(input_path: Path, recursive: bool = False) -> List[Path]:
    if input_path.is_file():
        return [input_path]
    it: Iterable[Path] = input_path.rglob("*") if recursive else input_path.iterdir()
    return sorted([p for p in it if p.is_file() and p.suffix.lower() in IMAGE_EXTS])


def read_yaml(path: Path) -> dict:
    try:
        import yaml
    except Exception as e:
        raise RuntimeError("需要 PyYAML：pip install pyyaml") from e
    return yaml.safe_load(path.expanduser().read_text(encoding="utf-8"))


def dump_yaml(path: Path, data: dict) -> None:
    try:
        import yaml
    except Exception as e:
        raise RuntimeError("需要 PyYAML：pip install pyyaml") from e
    path.write_text(yaml.safe_dump(data, allow_unicode=True, sort_keys=False), encoding="utf-8")


def read_matrix(data: dict, name: str) -> np.ndarray:
    item = data[name]
    return np.array(item["data"], dtype=np.float64).reshape(int(item["rows"]), int(item["cols"]))


def matrix_to_yaml(mat: np.ndarray) -> dict:
    mat = np.asarray(mat, dtype=np.float64)
    return {
        "rows": int(mat.shape[0]),
        "cols": int(mat.shape[1]),
        "data": [float(x) for x in mat.reshape(-1)],
    }


def parse_axis(axis: str) -> np.ndarray:
    axis = axis.strip().lower()
    if axis in {"+x", "x", "board+x", "+board_x"}:
        return np.array([1.0, 0.0], dtype=np.float64)
    if axis in {"-x", "board-x", "-board_x"}:
        return np.array([-1.0, 0.0], dtype=np.float64)
    if axis in {"+y", "y", "board+y", "+board_y"}:
        return np.array([0.0, 1.0], dtype=np.float64)
    if axis in {"-y", "board-y", "-board_y"}:
        return np.array([0.0, -1.0], dtype=np.float64)
    raise ValueError("axis 必须是 +x, -x, +y, -y 之一")


def normalize2(v: np.ndarray) -> np.ndarray:
    v = np.asarray(v, dtype=np.float64).reshape(2)
    n = float(np.linalg.norm(v))
    if n < 1e-9:
        raise ValueError("forward vector is too small")
    return v / n


def compute_vehicle_basis_in_board(data: dict, args) -> Tuple[np.ndarray, np.ndarray, np.ndarray, str]:
    """
    Return:
      origin_board_xy: vehicle origin expressed in board/ground XY
      forward_board: vehicle +X direction expressed in board/ground XY
      left_board: vehicle +Y direction expressed in board/ground XY
      note
    """
    T_ground_camera = read_matrix(data, "T_ground_camera")
    camera_xy = T_ground_camera[:2, 3].astype(np.float64)

    if args.origin == "camera-ground":
        origin = camera_xy.copy()
    elif args.origin == "board":
        origin = np.array([0.0, 0.0], dtype=np.float64)
    elif args.origin == "manual":
        origin = np.array([args.origin_board_x, args.origin_board_y], dtype=np.float64)
    else:
        raise ValueError(f"unknown origin mode: {args.origin}")

    if args.align == "camera-optical":
        R_ground_camera = T_ground_camera[:3, :3]
        # OpenCV camera +Z is optical/forward direction.
        optical_axis_in_ground = R_ground_camera[:, 2]
        forward = normalize2(optical_axis_in_ground[:2])
        note = "vehicle +X is camera optical axis projected to ground"
    elif args.align == "axis":
        forward = normalize2(parse_axis(args.vehicle_forward_axis))
        note = f"vehicle +X is board {args.vehicle_forward_axis}"
    elif args.align == "yaw":
        theta = math.radians(args.yaw_deg)
        # theta: angle from board +X to vehicle +X, positive toward board +Y.
        forward = np.array([math.cos(theta), math.sin(theta)], dtype=np.float64)
        note = f"vehicle +X yaw in board frame = {args.yaw_deg} deg"
    else:
        raise ValueError(f"unknown align mode: {args.align}")

    # Right-handed planar basis: left is +90deg rotation from forward.
    left = np.array([-forward[1], forward[0]], dtype=np.float64)
    if args.flip_left:
        left = -left
        note += "; left axis flipped"

    return origin, forward, left, note


def make_T_board_vehicle(origin_board_xy: np.ndarray, forward_board: np.ndarray, left_board: np.ndarray) -> np.ndarray:
    """
    Board XY = origin + forward * X_vehicle + left * Y_vehicle
    """
    T = np.eye(3, dtype=np.float64)
    T[0:2, 0] = forward_board.reshape(2)
    T[0:2, 1] = left_board.reshape(2)
    T[0:2, 2] = origin_board_xy.reshape(2)
    return T


def vehicle_to_bev_matrix(forward_min, forward_max, left_min, left_max, ppm) -> Tuple[np.ndarray, int, int]:
    """
    Vehicle frame:
      X forward, Y left.
    BEV image:
      u = (left_max - Y) * ppm
      v = (forward_max - X) * ppm
    So:
      +X forward appears upward.
      +Y left appears left.
    """
    out_w = int(round((left_max - left_min) * ppm))
    out_h = int(round((forward_max - forward_min) * ppm))
    if out_w <= 0 or out_h <= 0:
        raise ValueError("BEV范围或ppm不合法，输出尺寸 <= 0")

    H = np.array(
        [
            [0.0, -ppm, left_max * ppm],
            [-ppm, 0.0, forward_max * ppm],
            [0.0, 0.0, 1.0],
        ],
        dtype=np.float64,
    )
    return H, out_w, out_h


def transform_points_h(H: np.ndarray, pts_xy: np.ndarray) -> np.ndarray:
    pts = np.column_stack([pts_xy, np.ones(len(pts_xy), dtype=np.float64)])
    out = (H @ pts.T).T
    out = out[:, :2] / out[:, 2:3]
    return out


def make_vehicle_grid(forward_min, forward_max, left_min, left_max, step):
    lines = []

    xs = np.arange(np.ceil(forward_min / step) * step, forward_max + 1e-9, step)
    ys = np.arange(np.ceil(left_min / step) * step, left_max + 1e-9, step)

    # Constant lateral Y lines, forward direction segments
    for y in ys:
        lines.append(np.array([[forward_min, y], [forward_max, y]], dtype=np.float64))

    # Constant forward X lines, lateral segments
    for x in xs:
        lines.append(np.array([[x, left_min], [x, left_max]], dtype=np.float64))

    return lines


def draw_grid_on_undistorted(
    image: np.ndarray,
    H_vehicle_to_img: np.ndarray,
    forward_min: float,
    forward_max: float,
    left_min: float,
    left_max: float,
    step: float,
) -> np.ndarray:
    vis = image.copy()
    lines = make_vehicle_grid(forward_min, forward_max, left_min, left_max, step)

    for line in lines:
        pts = transform_points_h(H_vehicle_to_img, line)
        p0, p1 = np.round(pts).astype(int)
        cv2.line(vis, tuple(p0), tuple(p1), (0, 255, 255), 1)

    # Draw vehicle origin and axes.
    origin = transform_points_h(H_vehicle_to_img, np.array([[0.0, 0.0]], dtype=np.float64))[0]
    x_axis = transform_points_h(H_vehicle_to_img, np.array([[0.3, 0.0]], dtype=np.float64))[0]  # forward
    y_axis = transform_points_h(H_vehicle_to_img, np.array([[0.0, 0.3]], dtype=np.float64))[0]  # left

    o = tuple(np.round(origin).astype(int))
    cv2.circle(vis, o, 5, (0, 0, 255), -1)
    cv2.arrowedLine(vis, o, tuple(np.round(x_axis).astype(int)), (0, 0, 255), 2)   # forward red
    cv2.arrowedLine(vis, o, tuple(np.round(y_axis).astype(int)), (0, 255, 0), 2)   # left green
    cv2.putText(vis, "X forward", tuple(np.round(x_axis).astype(int)), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 0, 255), 2)
    cv2.putText(vis, "Y left", tuple(np.round(y_axis).astype(int)), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 255, 0), 2)
    return vis


def draw_grid_on_bev(
    bev: np.ndarray,
    forward_min: float,
    forward_max: float,
    left_min: float,
    left_max: float,
    ppm: float,
    step: float,
) -> np.ndarray:
    vis = bev.copy()
    H_vehicle_to_bev, _, _ = vehicle_to_bev_matrix(forward_min, forward_max, left_min, left_max, ppm)
    lines = make_vehicle_grid(forward_min, forward_max, left_min, left_max, step)
    for line in lines:
        pts = transform_points_h(H_vehicle_to_bev, line)
        p0, p1 = np.round(pts).astype(int)
        cv2.line(vis, tuple(p0), tuple(p1), (0, 255, 255), 1)
    return vis


def parse_args():
    p = argparse.ArgumentParser(description="Generate vehicle-forward BEV from ChArUco ground extrinsic.")

    p.add_argument("--extrinsic", type=Path, required=True, help="ground_extrinsic.yaml")
    p.add_argument("--input", type=Path, default=None, help="测试图片或目录；不填则只输出 vehicle_bev_extrinsic.yaml")
    p.add_argument("--output", type=Path, default=None, help="输出目录")
    p.add_argument("--recursive", action="store_true", help="递归读取图片")

    p.add_argument(
        "--align",
        choices=["camera-optical", "axis", "yaw"],
        default="camera-optical",
        help="车头方向定义方式。默认 camera-optical：相机光轴投影到地面作为车头方向。",
    )
    p.add_argument("--vehicle-forward-axis", default="+y", help="--align axis 时使用：+x/-x/+y/-y，表示哪个board轴是车头前方")
    p.add_argument("--yaw-deg", type=float, default=0.0, help="--align yaw 时使用：车头方向相对board +X的角度，逆时针为正")
    p.add_argument("--flip-left", action="store_true", help="如果左右镜像，打开这个选项")

    p.add_argument(
        "--origin",
        choices=["camera-ground", "board", "manual"],
        default="camera-ground",
        help="vehicle原点。默认 camera-ground：相机中心在地面的垂直投影。",
    )
    p.add_argument("--origin-board-x", type=float, default=0.0, help="--origin manual 时使用，vehicle原点在board坐标系下的X/m")
    p.add_argument("--origin-board-y", type=float, default=0.0, help="--origin manual 时使用，vehicle原点在board坐标系下的Y/m")

    p.add_argument("--forward-min", type=float, default=0.0, help="BEV前向最小值/m")
    p.add_argument("--forward-max", type=float, default=2.0, help="BEV前向最大值/m")
    p.add_argument("--left-min", type=float, default=-0.6, help="BEV左向最小值/m；负值是车右侧")
    p.add_argument("--left-max", type=float, default=0.6, help="BEV左向最大值/m；正值是车左侧")
    p.add_argument("--ppm", type=float, default=250.0, help="pixels per meter")

    p.add_argument("--alpha", type=float, default=0.0, help="去畸变new camera matrix alpha，建议保持0")
    p.add_argument("--draw-grid", action="store_true", help="保存原图网格overlay和BEV网格")
    p.add_argument("--grid-step", type=float, default=0.1, help="网格间距/m")
    p.add_argument("--no-undistorted-save", action="store_true", help="不保存去畸变图")

    return p.parse_args()


def main() -> int:
    args = parse_args()

    extrinsic_path = args.extrinsic.expanduser().resolve()
    data = read_yaml(extrinsic_path)

    K = read_matrix(data, "camera_matrix")
    dist = read_matrix(data, "distortion_coefficients").reshape(-1, 1)
    H_board_to_img = read_matrix(data, "H_ground_to_undistorted_image")
    H_img_to_board = read_matrix(data, "H_undistorted_image_to_ground")

    origin_board, forward_board, left_board, note = compute_vehicle_basis_in_board(data, args)
    T_board_vehicle = make_T_board_vehicle(origin_board, forward_board, left_board)
    T_vehicle_board = np.linalg.inv(T_board_vehicle)

    H_vehicle_to_img = H_board_to_img @ T_board_vehicle
    H_vehicle_to_img = H_vehicle_to_img / H_vehicle_to_img[2, 2]
    H_img_to_vehicle = T_vehicle_board @ H_img_to_board
    H_img_to_vehicle = H_img_to_vehicle / H_img_to_vehicle[2, 2]

    H_vehicle_to_bev, out_w, out_h = vehicle_to_bev_matrix(
        args.forward_min, args.forward_max, args.left_min, args.left_max, args.ppm
    )
    H_img_to_bev = H_vehicle_to_bev @ H_img_to_vehicle
    H_img_to_bev = H_img_to_bev / H_img_to_bev[2, 2]

    if args.output is None:
        if args.input is None:
            out_dir = extrinsic_path.parent / "vehicle_bev"
        else:
            inp = args.input.expanduser().resolve()
            out_dir = inp.parent / f"{inp.stem}_vehicle_bev" if inp.is_file() else inp.parent / f"{inp.name}_vehicle_bev"
    else:
        out_dir = args.output.expanduser().resolve()

    out_dir.mkdir(parents=True, exist_ok=True)

    vehicle_yaml = {
        "source_extrinsic": str(extrinsic_path),
        "coordinate_convention": {
            "vehicle_x": "forward",
            "vehicle_y": "left",
            "bev_up": "+vehicle_x_forward",
            "bev_left": "+vehicle_y_left",
            "homographies_apply_to": "undistorted image, alpha=0 recommended",
        },
        "alignment": {
            "mode": args.align,
            "note": note,
            "origin_mode": args.origin,
            "origin_board_xy_m": [float(origin_board[0]), float(origin_board[1])],
            "vehicle_forward_in_board_xy": [float(forward_board[0]), float(forward_board[1])],
            "vehicle_left_in_board_xy": [float(left_board[0]), float(left_board[1])],
        },
        "bev": {
            "forward_min_m": float(args.forward_min),
            "forward_max_m": float(args.forward_max),
            "left_min_m": float(args.left_min),
            "left_max_m": float(args.left_max),
            "pixels_per_meter": float(args.ppm),
            "output_width": int(out_w),
            "output_height": int(out_h),
        },
        "camera_matrix": matrix_to_yaml(K),
        "distortion_coefficients": matrix_to_yaml(dist.reshape(1, -1)),
        "T_board_vehicle_2d": matrix_to_yaml(T_board_vehicle),
        "T_vehicle_board_2d": matrix_to_yaml(T_vehicle_board),
        "H_vehicle_to_undistorted_image": matrix_to_yaml(H_vehicle_to_img),
        "H_undistorted_image_to_vehicle": matrix_to_yaml(H_img_to_vehicle),
        "H_vehicle_to_bev": matrix_to_yaml(H_vehicle_to_bev),
        "H_undistorted_image_to_bev": matrix_to_yaml(H_img_to_bev),
    }
    dump_yaml(out_dir / "vehicle_bev_extrinsic.yaml", vehicle_yaml)

    print("Vehicle BEV alignment")
    print("=" * 32)
    print(f"source: {extrinsic_path}")
    print(f"output: {out_dir}")
    print(f"align: {args.align}; {note}")
    print(f"origin in board [m]: {origin_board[0]:.6f}, {origin_board[1]:.6f}")
    print(f"forward in board: {forward_board[0]:.6f}, {forward_board[1]:.6f}")
    print(f"left in board: {left_board[0]:.6f}, {left_board[1]:.6f}")
    print(f"BEV size: {out_w} x {out_h}")

    if args.input is None:
        print("[DONE] 只输出 vehicle_bev_extrinsic.yaml")
        return 0

    input_path = args.input.expanduser().resolve()
    images = list_images(input_path, args.recursive)
    if not images:
        print(f"[ERROR] 没有找到测试图片: {input_path}", file=sys.stderr)
        return 2

    bev_dir = out_dir / "bev"
        overlay_dir.mkdir(exist_ok=True)
        bev_grid_dir.mkdir(exist_ok=True)

    rows = []
    warn_alpha = False
    for pth in images:
        img = cv2.imread(str(pth), cv2.IMREAD_COLOR)
        if img is None:
            rows.append({"filename": pth.name, "ok": 0, "reason": "imread failed"})
            continue

        h, w = img.shape[:2]
        new_K, _ = cv2.getOptimalNewCameraMatrix(K, dist, (w, h), alpha=args.alpha, newImgSize=(w, h))
        if abs(args.alpha) > 1e-9 and not warn_alpha:
            print("[WARN] alpha != 0 时，YAML里的H基于alpha=0，可能不严格匹配。建议保持 alpha=0。", file=sys.stderr)
            warn_alpha = True

        undist = cv2.undistort(img, K, dist, None, new_K)
        bev = cv2.warpPerspective(undist, H_img_to_bev, (out_w, out_h), flags=cv2.INTER_LINEAR)

        cv2.imwrite(str(bev_dir / f"{pth.stem}_vehicle_bev.png"), bev)
        if not args.no_undistorted_save:
            cv2.imwrite(str(undist_dir / f"{pth.stem}_undistorted.png"), undist)

        if args.draw_grid:
            overlay = draw_grid_on_undistorted(
                undist,
                H_vehicle_to_img,
                args.forward_min,
                args.forward_max,
                args.left_min,
                args.left_max,
                args.grid_step,
            )
            bev_grid = draw_grid_on_bev(
                bev,
                args.forward_min,
                args.forward_max,
                args.left_min,
                args.left_max,
                args.ppm,
                args.grid_step,
            )
            cv2.imwrite(str(overlay_dir / f"{pth.stem}_vehicle_grid.png"), overlay)
            cv2.imwrite(str(bev_grid_dir / f"{pth.stem}_vehicle_bev_grid.png"), bev_grid)

        rows.append({
            "filename": pth.name,
            "ok": 1,
            "width": w,
            "height": h,
            "bev_width": out_w,
            "bev_height": out_h,
            "reason": "ok",
        })

    with (out_dir / "process_log.csv").open("w", newline="", encoding="utf-8") as f:
        fields = ["filename", "ok", "width", "height", "bev_width", "bev_height", "reason"]
        writer = csv.DictWriter(f, fields)
        writer.writeheader()
        for r in rows:
            writer.writerow({k: r.get(k, "") for k in fields})

    print(f"[DONE] images processed: {len(images)}")
    print(f"  BEV: {bev_dir}")
    if args.draw_grid:
        print(f"  overlay_vehicle_grid: {overlay_dir}")
        print(f"  bev_vehicle_grid: {bev_grid_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
