#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Apply ChArUco intrinsic + ground extrinsic calibration to test images.

Input:
  - ground_extrinsic.yaml generated by charuco_ground_extrinsic.py
  - test images directory

Output:
  - undistorted images
  - BEV/IPM images
  - optional overlay images with a metric ground grid projected into the image

Typical usage:
  python3 apply_ground_bev.py \
    --extrinsic ~/calib/extrinsics/charuco_ground_extrinsic_out/ground_extrinsic.yaml \
    --input ~/calib/test \
    --output ~/calib/test_bev \
    --bev-x-min -0.5 --bev-x-max 1.5 \
    --bev-y-min -0.8 --bev-y-max 0.8 \
    --ppm 300 \
    --draw-grid
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Iterable, List, Tuple

import cv2
import numpy as np


IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp"}


def list_images(input_path: Path, recursive: bool = False) -> List[Path]:
    if input_path.is_file():
        return [input_path]
    it: Iterable[Path] = input_path.rglob("*") if recursive else input_path.iterdir()
    return sorted([p for p in it if p.is_file() and p.suffix.lower() in IMAGE_EXTS])


def read_yaml(path: Path) -> dict:
    try:
        import yaml
    except Exception:
        raise RuntimeError("需要 PyYAML：pip install pyyaml")
    return yaml.safe_load(path.expanduser().read_text(encoding="utf-8"))


def read_matrix(data: dict, name: str) -> np.ndarray:
    item = data[name]
    mat = np.array(item["data"], dtype=np.float64).reshape(int(item["rows"]), int(item["cols"]))
    return mat


def ground_to_bev_matrix(x_min: float, x_max: float, y_min: float, y_max: float, ppm: float) -> Tuple[np.ndarray, int, int]:
    out_w = int(round((x_max - x_min) * ppm))
    out_h = int(round((y_max - y_min) * ppm))
    if out_w <= 0 or out_h <= 0:
        raise ValueError("BEV范围或ppm不合法，输出尺寸 <= 0")

    # BEV pixel:
    #   u = (X - x_min) * ppm
    #   v = (y_max - Y) * ppm
    H_ground_to_bev = np.array(
        [
            [ppm, 0.0, -x_min * ppm],
            [0.0, -ppm, y_max * ppm],
            [0.0, 0.0, 1.0],
        ],
        dtype=np.float64,
    )
    return H_ground_to_bev, out_w, out_h


def make_metric_grid_points(x_min, x_max, y_min, y_max, step) -> Tuple[List[np.ndarray], List[np.ndarray]]:
    vertical_lines = []
    horizontal_lines = []

    xs = np.arange(np.ceil(x_min / step) * step, x_max + 1e-9, step)
    ys = np.arange(np.ceil(y_min / step) * step, y_max + 1e-9, step)

    for x in xs:
        vertical_lines.append(np.array([[x, y_min], [x, y_max]], dtype=np.float64))
    for y in ys:
        horizontal_lines.append(np.array([[x_min, y], [x_max, y]], dtype=np.float64))

    return vertical_lines, horizontal_lines


def transform_points_h(H: np.ndarray, pts_xy: np.ndarray) -> np.ndarray:
    pts = np.column_stack([pts_xy, np.ones(len(pts_xy), dtype=np.float64)])
    out = (H @ pts.T).T
    out = out[:, :2] / out[:, 2:3]
    return out


def draw_grid_on_undistorted(
    image: np.ndarray,
    H_ground_to_img: np.ndarray,
    x_min: float,
    x_max: float,
    y_min: float,
    y_max: float,
    step: float,
) -> np.ndarray:
    vis = image.copy()
    vertical_lines, horizontal_lines = make_metric_grid_points(x_min, x_max, y_min, y_max, step)

    for line in vertical_lines:
        pts = transform_points_h(H_ground_to_img, line)
        p0, p1 = np.round(pts).astype(int)
        cv2.line(vis, tuple(p0), tuple(p1), (0, 255, 255), 1)

    for line in horizontal_lines:
        pts = transform_points_h(H_ground_to_img, line)
        p0, p1 = np.round(pts).astype(int)
        cv2.line(vis, tuple(p0), tuple(p1), (0, 200, 0), 1)

    # Draw ground origin and axes.
    origin = transform_points_h(H_ground_to_img, np.array([[0.0, 0.0]], dtype=np.float64))[0]
    x_axis = transform_points_h(H_ground_to_img, np.array([[0.2, 0.0]], dtype=np.float64))[0]
    y_axis = transform_points_h(H_ground_to_img, np.array([[0.0, 0.2]], dtype=np.float64))[0]
    o = tuple(np.round(origin).astype(int))
    cv2.circle(vis, o, 5, (0, 0, 255), -1)
    cv2.arrowedLine(vis, o, tuple(np.round(x_axis).astype(int)), (0, 0, 255), 2)   # X red
    cv2.arrowedLine(vis, o, tuple(np.round(y_axis).astype(int)), (0, 255, 0), 2)   # Y green
    cv2.putText(vis, "X", tuple(np.round(x_axis).astype(int)), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)
    cv2.putText(vis, "Y", tuple(np.round(y_axis).astype(int)), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
    return vis


def draw_grid_on_bev(
    bev: np.ndarray,
    x_min: float,
    x_max: float,
    y_min: float,
    y_max: float,
    ppm: float,
    step: float,
) -> np.ndarray:
    vis = bev.copy()
    H_ground_to_bev, _, _ = ground_to_bev_matrix(x_min, x_max, y_min, y_max, ppm)
    vertical_lines, horizontal_lines = make_metric_grid_points(x_min, x_max, y_min, y_max, step)

    for line in vertical_lines:
        pts = transform_points_h(H_ground_to_bev, line)
        p0, p1 = np.round(pts).astype(int)
        cv2.line(vis, tuple(p0), tuple(p1), (0, 255, 255), 1)

    for line in horizontal_lines:
        pts = transform_points_h(H_ground_to_bev, line)
        p0, p1 = np.round(pts).astype(int)
        cv2.line(vis, tuple(p0), tuple(p1), (0, 200, 0), 1)

    return vis


def parse_args():
    p = argparse.ArgumentParser(description="Apply camera-ground extrinsic to test images and generate BEV.")
    p.add_argument("--extrinsic", type=Path, required=True, help="ground_extrinsic.yaml")
    p.add_argument("--input", type=Path, required=True, help="测试图片或目录")
    p.add_argument("--output", type=Path, default=None, help="输出目录，默认 input_bev")
    p.add_argument("--recursive", action="store_true", help="递归读取图片")

    p.add_argument("--bev-x-min", type=float, default=None, help="地面X最小值，单位m")
    p.add_argument("--bev-x-max", type=float, default=None, help="地面X最大值，单位m")
    p.add_argument("--bev-y-min", type=float, default=None, help="地面Y最小值，单位m")
    p.add_argument("--bev-y-max", type=float, default=None, help="地面Y最大值，单位m")
    p.add_argument("--ppm", type=float, default=None, help="pixels per meter")

    p.add_argument("--alpha", type=float, default=0.0, help="去畸变new camera matrix的alpha。必须和外参脚本一致，默认0")
    p.add_argument("--draw-grid", action="store_true", help="保存带地面网格的overlay图")
    p.add_argument("--grid-step", type=float, default=0.1, help="网格间距，单位m")
    p.add_argument("--no-undistorted-save", action="store_true", help="不保存去畸变图，只保存BEV")
    return p.parse_args()


def main() -> int:
    args = parse_args()

    data = read_yaml(args.extrinsic)
    K = read_matrix(data, "camera_matrix")
    dist = read_matrix(data, "distortion_coefficients").reshape(-1, 1)
    H_img_to_ground = read_matrix(data, "H_undistorted_image_to_ground")
    H_ground_to_img = read_matrix(data, "H_ground_to_undistorted_image")

    bev_cfg = data.get("bev", {})
    x_min = args.bev_x_min if args.bev_x_min is not None else float(bev_cfg.get("x_min_m", -0.5))
    x_max = args.bev_x_max if args.bev_x_max is not None else float(bev_cfg.get("x_max_m", 1.5))
    y_min = args.bev_y_min if args.bev_y_min is not None else float(bev_cfg.get("y_min_m", -0.8))
    y_max = args.bev_y_max if args.bev_y_max is not None else float(bev_cfg.get("y_max_m", 0.8))
    ppm = args.ppm if args.ppm is not None else float(bev_cfg.get("pixels_per_meter", 300))

    input_path = args.input.expanduser().resolve()
    if args.output is None:
        out_dir = input_path.parent / f"{input_path.stem}_bev" if input_path.is_file() else input_path.parent / f"{input_path.name}_bev"
    else:
        out_dir = args.output.expanduser().resolve()

    bev_dir = out_dir / "bev"
    undist_dir = out_dir / "undistorted"
    overlay_dir = out_dir / "overlay_grid"
    bev_grid_dir = out_dir / "bev_grid"
    bev_dir.mkdir(parents=True, exist_ok=True)
    if not args.no_undistorted_save:
        undist_dir.mkdir(parents=True, exist_ok=True)
    if args.draw_grid:
        overlay_dir.mkdir(parents=True, exist_ok=True)
        bev_grid_dir.mkdir(parents=True, exist_ok=True)

    images = list_images(input_path, recursive=args.recursive)
    if not images:
        print(f"[ERROR] 没有找到测试图片: {input_path}", file=sys.stderr)
        return 2

    H_ground_to_bev, out_w, out_h = ground_to_bev_matrix(x_min, x_max, y_min, y_max, ppm)
    H_img_to_bev = H_ground_to_bev @ H_img_to_ground

    csv_rows = []
    first_size = None

    print(f"[INFO] Images: {len(images)}")
    print(f"[INFO] Output BEV size: {out_w} x {out_h}")
    print(f"[INFO] BEV range: X[{x_min}, {x_max}] m, Y[{y_min}, {y_max}] m, ppm={ppm}")

    for pth in images:
        img = cv2.imread(str(pth), cv2.IMREAD_COLOR)
        if img is None:
            csv_rows.append({"filename": pth.name, "ok": 0, "reason": "imread failed"})
            continue

        h, w = img.shape[:2]
        if first_size is None:
            first_size = (w, h)

        new_K, _ = cv2.getOptimalNewCameraMatrix(K, dist, (w, h), alpha=args.alpha, newImgSize=(w, h))
        # Safety check: H in YAML was computed with alpha=0 and the original resolution.
        # If alpha or resolution changes, recompute homography from extrinsic instead. This script expects alpha=0.
        if abs(args.alpha) > 1e-9:
            print("[WARN] alpha != 0 时，YAML里的 H_undistorted_image_to_ground 可能不再严格匹配。建议 alpha=0。", file=sys.stderr)

        undist = cv2.undistort(img, K, dist, None, new_K)
        bev = cv2.warpPerspective(undist, H_img_to_bev, (out_w, out_h), flags=cv2.INTER_LINEAR)

        cv2.imwrite(str(bev_dir / f"{pth.stem}_bev.png"), bev)
        if not args.no_undistorted_save:
            cv2.imwrite(str(undist_dir / f"{pth.stem}_undistorted.png"), undist)

        if args.draw_grid:
            overlay = draw_grid_on_undistorted(undist, H_ground_to_img, x_min, x_max, y_min, y_max, args.grid_step)
            bev_grid = draw_grid_on_bev(bev, x_min, x_max, y_min, y_max, ppm, args.grid_step)
            cv2.imwrite(str(overlay_dir / f"{pth.stem}_grid.png"), overlay)
            cv2.imwrite(str(bev_grid_dir / f"{pth.stem}_bev_grid.png"), bev_grid)

        csv_rows.append({
            "filename": pth.name,
            "ok": 1,
            "width": w,
            "height": h,
            "bev_width": out_w,
            "bev_height": out_h,
            "reason": "ok",
        })

    with (out_dir / "process_log.csv").open("w", newline="", encoding="utf-8") as f:
        fields = ["filename", "ok", "width", "height", "bev_width", "bev_height", "reason"]
        writer = csv.DictWriter(f, fields)
        writer.writeheader()
        for r in csv_rows:
            writer.writerow({k: r.get(k, "") for k in fields})

    print(f"[DONE] 输出目录: {out_dir}")
    print(f"  BEV: {bev_dir}")
    if not args.no_undistorted_save:
        print(f"  undistorted: {undist_dir}")
    if args.draw_grid:
        print(f"  overlay_grid: {overlay_dir}")
        print(f"  bev_grid: {bev_grid_dir}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
