#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
OpenCV editor for correcting semantic-segmentation masks produced by
infer_pt_bev_semantic_071801.py.

The default paths are configured for the 071801.pt second-round labeling run.

Mask ID convention:
    0 = background
    1 = P
    2 = A_DaTing
    3 = B_TongDao
    4 = C_ZhenLiaoShi
    5 = JinQu

The corrected masks remain single-channel uint8 PNG files and can be used
directly as semantic-segmentation labels.

Window layout:
    left   : editable overlay
    middle : overlay with connected-region class names
    right  : class legend and pixel ratios
    top    : status and keyboard controls
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable

import cv2
import numpy as np


IMAGE_EXTS = {
    ".jpg", ".jpeg", ".png", ".bmp",
    ".tif", ".tiff", ".webp",
}

BACKGROUND_ID = 0

CLASS_NAMES = {
    0: "background",
    1: "P",
    2: "A_DaTing",
    3: "B_TongDao",
    4: "C_ZhenLiaoShi",
    5: "JinQu",
}

# OpenCV BGR colors; these are visualization colors only.
COLORS_BGR = {
    0: (35, 35, 35),       # background
    1: (255, 255, 255),    # P
    2: (255, 255, 0),      # A_DaTing
    3: (0, 165, 255),      # B_TongDao
    4: (255, 0, 255),      # C_ZhenLiaoShi
    5: (255, 0, 0),        # JinQu
}

COLOR_NAMES = {
    0: "dark gray",
    1: "white",
    2: "cyan",
    3: "orange",
    4: "magenta",
    5: "blue",
}

RGB_VALUES = {
    0: (35, 35, 35),
    1: (255, 255, 255),
    2: (0, 255, 255),
    3: (255, 165, 0),
    4: (255, 0, 255),
    5: (0, 0, 255),
}

HUD_HEIGHT = 105
LEGEND_WIDTH = 500

DEFAULT_IMAGES = Path(
    "/home/xhm/Desktop/relocate_ws/data/extracted/bev_all/2026-06-28_01-05-54"
)
DEFAULT_RUN_ROOT = Path(
    "/home/xhm/Desktop/relocate_ws/data/extracted/seg_pt/"
    "2026-06-28_01-05-54_071801"
)
DEFAULT_MASKS = DEFAULT_RUN_ROOT / "masks_id"
DEFAULT_OUT_MASKS = DEFAULT_RUN_ROOT / "masks_corrected"
DEFAULT_OUT_OVERLAYS = DEFAULT_RUN_ROOT / "overlays_corrected"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Manually correct semantic masks generated by 071801.pt. "
            "The original drawing and saving behavior is preserved."
        )
    )
    parser.add_argument(
        "--images",
        type=Path,
        default=DEFAULT_IMAGES,
        help=f"BEV image file or directory. Default: {DEFAULT_IMAGES}",
    )
    parser.add_argument(
        "--masks",
        type=Path,
        default=DEFAULT_MASKS,
        help=f"Input PT-generated masks_id directory. Default: {DEFAULT_MASKS}",
    )
    parser.add_argument(
        "--out-masks",
        type=Path,
        default=DEFAULT_OUT_MASKS,
        help=(
            "Output directory for corrected single-channel PNG masks. "
            f"Default: {DEFAULT_OUT_MASKS}"
        ),
    )
    parser.add_argument(
        "--out-overlays",
        type=Path,
        default=DEFAULT_OUT_OVERLAYS,
        help=(
            "Output directory for corrected overlay images. "
            f"Default: {DEFAULT_OUT_OVERLAYS}"
        ),
    )
    parser.add_argument(
        "--recursive",
        dest="recursive",
        action="store_true",
        help="Recursively search the image directory. This is the default.",
    )
    parser.add_argument(
        "--no-recursive",
        dest="recursive",
        action="store_false",
        help="Search only the image directory itself.",
    )
    parser.set_defaults(recursive=True)
    parser.add_argument(
        "--alpha",
        type=float,
        default=0.45,
        help="Mask opacity in overlays. Default: 0.45.",
    )
    parser.add_argument(
        "--brush-size",
        type=int,
        default=8,
        help="Initial brush radius in pixels. Default: 8.",
    )
    parser.add_argument(
        "--start-class",
        type=int,
        default=1,
        help="Initial class ID, 0..5. Default: 1 (P).",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=0,
        help="Zero-based image index to open first. Default: 0.",
    )
    parser.add_argument(
        "--min-area-text",
        type=int,
        default=250,
        help="Minimum connected-region area for drawing a class name. Default: 250.",
    )
    parser.add_argument(
        "--window-width",
        type=int,
        default=1500,
        help="Initial OpenCV window width. Default: 1500.",
    )
    parser.add_argument(
        "--window-height",
        type=int,
        default=650,
        help="Initial OpenCV window height. Default: 650.",
    )
    return parser.parse_args()


def list_images(path: Path, recursive: bool) -> list[Path]:
    if path.is_file():
        if path.suffix.lower() not in IMAGE_EXTS:
            raise ValueError(f"Unsupported image file: {path}")
        return [path]

    iterator: Iterable[Path]
    iterator = path.rglob("*") if recursive else path.iterdir()

    return sorted(
        item
        for item in iterator
        if item.is_file() and item.suffix.lower() in IMAGE_EXTS
    )


def relative_image_path(image_path: Path, image_root: Path) -> Path:
    if image_root.is_file():
        return Path(image_path.name)
    return image_path.relative_to(image_root)


def validate_mask_ids(mask: np.ndarray, source: Path) -> None:
    unique_ids = set(int(value) for value in np.unique(mask))
    valid_ids = set(CLASS_NAMES)
    invalid_ids = sorted(unique_ids - valid_ids)

    if invalid_ids:
        raise RuntimeError(
            f"Mask contains invalid class IDs {invalid_ids}: {source}. "
            f"Expected only {sorted(valid_ids)}."
        )


def colorize_mask(mask_id: np.ndarray) -> np.ndarray:
    height, width = mask_id.shape
    color = np.zeros((height, width, 3), dtype=np.uint8)

    for class_id, bgr in COLORS_BGR.items():
        color[mask_id == class_id] = bgr

    return color


def make_overlay(
    image_bgr: np.ndarray,
    mask_id: np.ndarray,
    alpha: float,
) -> np.ndarray:
    color = colorize_mask(mask_id)
    return cv2.addWeighted(
        image_bgr,
        1.0 - alpha,
        color,
        alpha,
        0.0,
    )


def draw_title(image: np.ndarray, title: str) -> np.ndarray:
    output = image.copy()
    cv2.rectangle(
        output,
        (0, 0),
        (output.shape[1], 30),
        (0, 0, 0),
        -1,
    )
    cv2.putText(
        output,
        title,
        (8, 22),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.58,
        (255, 255, 255),
        2,
        cv2.LINE_AA,
    )
    return output


def draw_region_labels(
    visualization: np.ndarray,
    mask_id: np.ndarray,
    min_area: int,
) -> np.ndarray:
    output = visualization.copy()

    # Background is deliberately not labeled in the image.
    for class_id in range(1, 6):
        name = CLASS_NAMES[class_id]
        binary = (mask_id == class_id).astype(np.uint8)

        count, labels, stats, centroids = cv2.connectedComponentsWithStats(
            binary,
            connectivity=8,
        )

        for component_id in range(1, count):
            area = int(stats[component_id, cv2.CC_STAT_AREA])
            if area < min_area:
                continue

            center_x, center_y = centroids[component_id]
            text = f"{class_id}:{name}"
            text_x = int(center_x) - 55
            text_y = int(center_y)

            cv2.putText(
                output,
                text,
                (text_x, text_y),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.45,
                (0, 0, 0),
                3,
                cv2.LINE_AA,
            )
            cv2.putText(
                output,
                text,
                (text_x, text_y),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.45,
                (255, 255, 255),
                1,
                cv2.LINE_AA,
            )

    return output


def draw_color_legend(
    mask_id: np.ndarray,
    height: int,
    width: int = LEGEND_WIDTH,
) -> np.ndarray:
    panel = np.full((height, width, 3), 35, dtype=np.uint8)
    total_pixels = mask_id.size

    cv2.putText(
        panel,
        "semantic class legend",
        (12, 24),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.62,
        (255, 255, 255),
        2,
        cv2.LINE_AA,
    )
    cv2.putText(
        panel,
        "mask pixel value == semantic class ID",
        (12, 48),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.42,
        (210, 210, 210),
        1,
        cv2.LINE_AA,
    )

    unique_ids = sorted(int(value) for value in np.unique(mask_id))
    pred_text = "current IDs: " + ",".join(map(str, unique_ids))
    cv2.putText(
        panel,
        pred_text[:58],
        (12, 70),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.40,
        (180, 220, 255),
        1,
        cv2.LINE_AA,
    )

    y = 98
    row_height = 36

    for class_id in range(6):
        name = CLASS_NAMES[class_id]
        color_bgr = COLORS_BGR[class_id]
        color_name = COLOR_NAMES[class_id]
        rgb = RGB_VALUES[class_id]

        area = int(np.sum(mask_id == class_id))
        ratio = area / total_pixels * 100.0

        cv2.rectangle(
            panel,
            (12, y - 14),
            (38, y + 10),
            color_bgr,
            -1,
        )
        cv2.rectangle(
            panel,
            (12, y - 14),
            (38, y + 10),
            (255, 255, 255),
            1,
        )

        line1 = f"{class_id}: {name}  {color_name}"
        line2 = f"RGB={rgb}  {ratio:.1f}%"

        cv2.putText(
            panel,
            line1,
            (48, y),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.40,
            (255, 255, 255),
            1,
            cv2.LINE_AA,
        )
        cv2.putText(
            panel,
            line2,
            (48, y + 17),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.34,
            (200, 200, 200),
            1,
            cv2.LINE_AA,
        )

        y += row_height

    return panel


def draw_hud(
    width: int,
    current_class: int,
    brush_size: int,
    index: int,
    total: int,
    image_name: str,
    dirty: bool,
    source_kind: str,
) -> np.ndarray:
    panel = np.full((HUD_HEIGHT, width, 3), 35, dtype=np.uint8)

    status = "UNSAVED" if dirty else "saved"
    status_color = (0, 180, 255) if dirty else (180, 255, 180)

    line1 = (
        f"[{index + 1}/{total}] {image_name}    "
        f"{status}    source={source_kind}"
    )
    line2 = (
        f"current: {current_class}:{CLASS_NAMES[current_class]}    "
        f"brush radius: {brush_size}"
    )
    line3 = (
        "0 background | 1 P | 2 A_DaTing | 3 B_TongDao | "
        "4 C_ZhenLiaoShi | 5 JinQu"
    )
    line4 = (
        "left draw | right erase(bg) | s save | n next | p prev | "
        "[ ] brush | c clear | r reload | q quit"
    )

    cv2.putText(
        panel,
        line1,
        (10, 23),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.52,
        status_color,
        1,
        cv2.LINE_AA,
    )
    cv2.putText(
        panel,
        line2,
        (10, 49),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.52,
        COLORS_BGR[current_class],
        2,
        cv2.LINE_AA,
    )
    cv2.putText(
        panel,
        line3,
        (10, 74),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.43,
        (220, 220, 220),
        1,
        cv2.LINE_AA,
    )
    cv2.putText(
        panel,
        line4,
        (10, 96),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.43,
        (220, 220, 220),
        1,
        cv2.LINE_AA,
    )

    return panel


def compose_editor_view(
    image_bgr: np.ndarray,
    mask_id: np.ndarray,
    alpha: float,
    current_class: int,
    brush_size: int,
    index: int,
    total: int,
    image_name: str,
    dirty: bool,
    source_kind: str,
    min_area_text: int,
) -> np.ndarray:
    editable_overlay = make_overlay(image_bgr, mask_id, alpha)
    labeled_overlay = draw_region_labels(
        editable_overlay,
        mask_id,
        min_area=min_area_text,
    )

    editable_overlay = draw_title(
        editable_overlay,
        "edit overlay - draw here",
    )
    labeled_overlay = draw_title(
        labeled_overlay,
        "overlay + region class names",
    )
    legend = draw_color_legend(
        mask_id,
        height=image_bgr.shape[0],
        width=LEGEND_WIDTH,
    )

    body = np.hstack([
        editable_overlay,
        labeled_overlay,
        legend,
    ])

    hud = draw_hud(
        width=body.shape[1],
        current_class=current_class,
        brush_size=brush_size,
        index=index,
        total=total,
        image_name=image_name,
        dirty=dirty,
        source_kind=source_kind,
    )

    return np.vstack([hud, body])


class SemanticMaskEditor:
    def __init__(self, args: argparse.Namespace):
        self.image_root = args.images.expanduser().resolve()
        self.mask_root = args.masks.expanduser().resolve()
        self.output_mask_root = args.out_masks.expanduser().resolve()
        self.output_overlay_root = args.out_overlays.expanduser().resolve()

        self.recursive = args.recursive
        self.alpha = args.alpha
        self.brush_size = args.brush_size
        self.current_class = args.start_class
        self.min_area_text = args.min_area_text
        self.window_width = args.window_width
        self.window_height = args.window_height

        self.images = list_images(self.image_root, self.recursive)
        if not self.images:
            raise RuntimeError(f"No images found: {self.image_root}")

        if not self.mask_root.exists():
            raise RuntimeError(f"Input mask path does not exist: {self.mask_root}")

        self.output_mask_root.mkdir(parents=True, exist_ok=True)
        self.output_overlay_root.mkdir(parents=True, exist_ok=True)

        self.index = int(np.clip(args.start_index, 0, len(self.images) - 1))
        self.image: np.ndarray | None = None
        self.mask: np.ndarray | None = None
        self.relative_path: Path | None = None
        self.source_kind = ""

        self.dirty = False
        self.drawing = False
        self.erase_mode = False

        self.window_name = "OpenCV BEV Semantic Mask Editor"

    def paths_for_current(self) -> tuple[Path, Path, Path]:
        image_path = self.images[self.index]
        relative_path = relative_image_path(image_path, self.image_root)

        raw_mask_path = (self.mask_root / relative_path).with_suffix(".png")
        edited_mask_path = (
            self.output_mask_root / relative_path
        ).with_suffix(".png")

        return relative_path, raw_mask_path, edited_mask_path

    def load_current(self) -> None:
        image_path = self.images[self.index]
        relative_path, raw_mask_path, edited_mask_path = self.paths_for_current()

        image = cv2.imread(str(image_path), cv2.IMREAD_COLOR)
        if image is None:
            raise RuntimeError(f"Failed to read image: {image_path}")

        if edited_mask_path.exists():
            mask_path = edited_mask_path
            source_kind = "edited"
        else:
            mask_path = raw_mask_path
            source_kind = "pt_auto"

        if not mask_path.exists():
            raise RuntimeError(
                f"Mask not found for image {image_path.name}: {mask_path}"
            )

        mask = cv2.imread(str(mask_path), cv2.IMREAD_UNCHANGED)
        if mask is None:
            raise RuntimeError(f"Failed to read mask: {mask_path}")

        if mask.ndim == 3:
            # A semantic label must be one channel. Reading channel 0 is allowed
            # only for accidental 3-channel copies whose channels are identical.
            if not (
                np.array_equal(mask[:, :, 0], mask[:, :, 1])
                and np.array_equal(mask[:, :, 1], mask[:, :, 2])
            ):
                raise RuntimeError(
                    f"Mask is a non-grayscale 3-channel image: {mask_path}"
                )
            mask = mask[:, :, 0]

        if not np.issubdtype(mask.dtype, np.integer):
            raise RuntimeError(
                f"Mask must contain integer class IDs: {mask_path}, dtype={mask.dtype}"
            )

        mask = mask.astype(np.uint8)
        validate_mask_ids(mask, mask_path)

        height, width = image.shape[:2]
        if mask.shape != (height, width):
            mask = cv2.resize(
                mask,
                (width, height),
                interpolation=cv2.INTER_NEAREST,
            )
            validate_mask_ids(mask, mask_path)

        self.image = image
        self.mask = mask
        self.relative_path = relative_path
        self.source_kind = source_kind
        self.dirty = False
        self.drawing = False
        self.erase_mode = False

    def save_current(self) -> None:
        assert self.image is not None
        assert self.mask is not None
        assert self.relative_path is not None

        validate_mask_ids(self.mask, self.relative_path)

        mask_path = (
            self.output_mask_root / self.relative_path
        ).with_suffix(".png")
        overlay_path = (
            self.output_overlay_root / self.relative_path
        ).with_suffix(".jpg")

        mask_path.parent.mkdir(parents=True, exist_ok=True)
        overlay_path.parent.mkdir(parents=True, exist_ok=True)

        # PNG is required because class IDs must not be changed by compression.
        if not cv2.imwrite(str(mask_path), self.mask):
            raise RuntimeError(f"Failed to save mask: {mask_path}")

        overlay = make_overlay(
            self.image,
            self.mask,
            alpha=self.alpha,
        )
        overlay = draw_region_labels(
            overlay,
            self.mask,
            min_area=self.min_area_text,
        )

        if not cv2.imwrite(str(overlay_path), overlay):
            raise RuntimeError(f"Failed to save overlay: {overlay_path}")

        self.dirty = False
        self.source_kind = "edited"

        print(f"[SAVE] {self.images[self.index].name}")
        print(f"       mask   : {mask_path}")
        print(f"       overlay: {overlay_path}")

    def render(self) -> None:
        assert self.image is not None
        assert self.mask is not None

        canvas = compose_editor_view(
            image_bgr=self.image,
            mask_id=self.mask,
            alpha=self.alpha,
            current_class=self.current_class,
            brush_size=self.brush_size,
            index=self.index,
            total=len(self.images),
            image_name=self.images[self.index].name,
            dirty=self.dirty,
            source_kind=self.source_kind,
            min_area_text=self.min_area_text,
        )
        cv2.imshow(self.window_name, canvas)

    def paint(self, x: int, y: int, class_id: int) -> None:
        assert self.mask is not None

        height, width = self.mask.shape
        x = int(np.clip(x, 0, width - 1))
        y = int(np.clip(y, 0, height - 1))

        # LINE_8 is intentional. Anti-aliased drawing would create invalid
        # intermediate pixel values in a semantic class-ID mask.
        cv2.circle(
            self.mask,
            (x, y),
            self.brush_size,
            int(class_id),
            thickness=-1,
            lineType=cv2.LINE_8,
        )
        self.dirty = True

    def mouse_callback(
        self,
        event: int,
        x: int,
        y: int,
        flags: int,
        param,
    ) -> None:
        del flags, param

        assert self.image is not None

        image_height, image_width = self.image.shape[:2]
        image_y = y - HUD_HEIGHT

        if image_y < 0 or image_y >= image_height:
            return

        # Editing is allowed only on the left panel.
        if x < 0 or x >= image_width:
            return

        image_x = x

        if event == cv2.EVENT_LBUTTONDOWN:
            self.drawing = True
            self.erase_mode = False
            self.paint(image_x, image_y, self.current_class)

        elif event == cv2.EVENT_RBUTTONDOWN:
            self.drawing = True
            self.erase_mode = True
            self.paint(image_x, image_y, BACKGROUND_ID)

        elif event == cv2.EVENT_MOUSEMOVE and self.drawing:
            class_id = BACKGROUND_ID if self.erase_mode else self.current_class
            self.paint(image_x, image_y, class_id)

        elif event in (cv2.EVENT_LBUTTONUP, cv2.EVENT_RBUTTONUP):
            self.drawing = False
            self.erase_mode = False

    def go_to_image(self, new_index: int) -> None:
        if self.dirty:
            print("[WARN] Unsaved changes. Press s before changing images.")
            return

        new_index = int(np.clip(new_index, 0, len(self.images) - 1))
        if new_index == self.index:
            return

        self.index = new_index
        self.load_current()

    def print_controls(self) -> None:
        print("=" * 82)
        print("OpenCV BEV Semantic Mask Editor - 071801.pt round")
        print("")
        print("Semantic mask IDs:")
        for class_id, class_name in CLASS_NAMES.items():
            print(f"  {class_id}: {class_name}")
        print("")
        print("Controls:")
        print("  0: background")
        print("  1: P")
        print("  2: A_DaTing")
        print("  3: B_TongDao")
        print("  4: C_ZhenLiaoShi")
        print("  5: JinQu")
        print("  left mouse : draw selected class on the left panel")
        print("  right mouse: erase to background=0")
        print("  [ / ]      : decrease / increase brush radius")
        print("  s          : save corrected PNG mask and overlay")
        print("  n / p      : next / previous image")
        print("  c          : clear entire mask to background=0")
        print("  r          : reload current image, discarding unsaved changes")
        print("  q or ESC   : quit")
        print("=" * 82)

    def run(self) -> None:
        self.load_current()

        cv2.namedWindow(self.window_name, cv2.WINDOW_NORMAL)
        cv2.resizeWindow(
            self.window_name,
            self.window_width,
            self.window_height,
        )
        cv2.setMouseCallback(
            self.window_name,
            self.mouse_callback,
        )

        self.print_controls()

        while True:
            self.render()
            key = cv2.waitKey(20) & 0xFF

            if key == 255:
                continue

            if key in (ord("q"), 27):
                if self.dirty:
                    print("[WARN] Unsaved changes. Press s before quitting.")
                    continue
                break

            if key in (
                ord("0"), ord("1"), ord("2"),
                ord("3"), ord("4"), ord("5"),
            ):
                self.current_class = int(chr(key))
                print(
                    f"[CLASS] {self.current_class}: "
                    f"{CLASS_NAMES[self.current_class]}"
                )

            elif key == ord("["):
                self.brush_size = max(1, self.brush_size - 2)
                print(f"[BRUSH] {self.brush_size}")

            elif key == ord("]"):
                self.brush_size = min(100, self.brush_size + 2)
                print(f"[BRUSH] {self.brush_size}")

            elif key == ord("s"):
                self.save_current()

            elif key == ord("n"):
                self.go_to_image(self.index + 1)

            elif key == ord("p"):
                self.go_to_image(self.index - 1)

            elif key == ord("c"):
                assert self.mask is not None
                self.mask[:, :] = BACKGROUND_ID
                self.dirty = True
                print("[CLEAR] Mask set to background=0")

            elif key == ord("r"):
                self.load_current()
                print("[RELOAD] Current image")

        cv2.destroyAllWindows()


def main() -> int:
    args = parse_args()

    if not 0.0 <= args.alpha <= 1.0:
        print("[ERROR] --alpha must be in [0, 1]", file=sys.stderr)
        return 1

    if args.brush_size < 1:
        print("[ERROR] --brush-size must be >= 1", file=sys.stderr)
        return 1

    if args.start_class not in CLASS_NAMES:
        print("[ERROR] --start-class must be in 0..5", file=sys.stderr)
        return 1

    if args.min_area_text < 1:
        print("[ERROR] --min-area-text must be >= 1", file=sys.stderr)
        return 1

    try:
        editor = SemanticMaskEditor(args)
        editor.run()
    except Exception as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
